#version 460 core

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout(binding = 0, rgba32f) uniform image2D image;

void main() {

    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);

    // Create a colour gradient using the x and y coordinates
    float r = float(coord.x) / float(imageSize(image).x);
    float g = float(coord.y) / float(imageSize(image).y);
    float b = 0.0;

    // Write the pixel to the image
    imageStore(image, coord, vec4(r, g, b, 1.0));
}